//update ES6
export const Rules = {
	access: ["parseAccess"],
	alias: ["parseNamePath", "ensureEnd"],
	augments: ["parseType", "parseNamePathOptional", "ensureEnd"],
	constructor: ["parseType", "parseNamePathOptional", "ensureEnd"],
	class: ["parseType", "parseNamePathOptional", "ensureEnd"],
	extends: ["parseType", "parseNamePathOptional", "ensureEnd"],
	example: ["parseCaption"],
	deprecated: ["parseDescription"],
	global: ["ensureEnd"],
	inner: ["ensureEnd"],
	instance: ["ensureEnd"],
	kind: ["parseKind"],
	mixes: ["parseNamePath", "ensureEnd"],
	mixin: ["parseNamePathOptional", "ensureEnd"],
	member: ["parseType", "parseNamePathOptional", "ensureEnd"],
	method: ["parseNamePathOptional", "ensureEnd"],
	module: ["parseType", "parseNamePathOptional", "ensureEnd"],
	func: ["parseNamePathOptional", "ensureEnd"],
	function: ["parseNamePathOptional", "ensureEnd"],
	var: ["parseType", "parseNamePathOptional", "ensureEnd"],
	name: ["parseNamePath", "ensureEnd"],
	namespace: ["parseType", "parseNamePathOptional", "ensureEnd"],
	private: ["parseType", "parseDescription"],
	protected: ["parseType", "parseDescription"],
	public: ["parseType", "parseDescription"],
	readonly: ["ensureEnd"],
	requires: ["parseNamePath", "ensureEnd"],
	since: ["parseDescription"],
	static: ["ensureEnd"],
	summary: ["parseDescription"],
	this: ["parseThis", "ensureEnd"],
	todo: ["parseDescription"],
	typedef: ["parseType", "parseNamePathOptional"],
	variation: ["parseVariation"],
	version: ["parseDescription"],
};
